# Generated by Django 2.2.12 on 2021-05-10 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('author', models.CharField(max_length=64)),
                ('description', models.TextField(max_length=1000)),
                ('added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
